# Generated by Django 6.1 on 2026-08-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('parent_id', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(default='PARTICULIER', max_length=20)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('entreprise', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField()),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('frais_acquisition', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cout_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mode_paiement', models.CharField(default='ESPECES', max_length=20)),
                ('statut', models.CharField(default='VALIDE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('cle', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('valeur', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=160)),
                ('entreprise', models.CharField(blank=True, max_length=160)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('pays', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='VENDEUR', max_length=10)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(blank=True, max_length=120)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=180)),
                ('marque', models.CharField(blank=True, max_length=120)),
                ('modele', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('type_tracabilite', models.CharField(default='LOT', max_length=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('seuil_min', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(default='ACTIF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.category')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('quantite_initiale', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantite_restante', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cout_unitaire_reel', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pos.product')),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remise_totale', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mode_paiement', models.CharField(default='ESPECES', max_length=20)),
                ('statut_paiement', models.CharField(default='PAYE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.customer')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.user')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('produit_nom', models.CharField(max_length=180)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unite_id', models.TextField(blank=True)),
                ('lot_id', models.TextField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pos.sale')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.supplier'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('etat', models.CharField(default='DISPONIBLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.purchase')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('type', models.CharField(max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(max_length=40)),
                ('motif', models.CharField(max_length=120)),
                ('stock_avant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stock_apres', models.DecimalField(decimal_places=2, max_digits=14)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.user')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('produit_nom', models.CharField(max_length=180)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('motif', models.CharField(max_length=120)),
                ('gravite', models.CharField(default='MOYENNE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.sale')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('categorie', models.CharField(max_length=80)),
                ('sous_categorie', models.CharField(blank=True, max_length=80)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('beneficiaire', models.CharField(blank=True, max_length=160)),
                ('mode_paiement', models.CharField(default='ESPECES', max_length=20)),
                ('type', models.CharField(default='GENERALE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.user')),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('type', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('montant_entree', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_sortie', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mode_paiement', models.CharField(blank=True, max_length=20)),
                ('categorie', models.CharField(blank=True, max_length=80)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.user')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=40)),
                ('module', models.CharField(max_length=40)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('details', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.user')),
            ],
        ),
    ]
