# Generated by Django 6.1 on 2026-08-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_copy_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='statut',
            field=models.CharField(default='PAYEE', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='statut_livraison',
            field=models.CharField(default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='statut_paiement',
            field=models.CharField(default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='VENDEUR', max_length=20),
        ),
    ]
