# Generated by Django 6.1 on 2026-08-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0005_sale_statut_sale_statut_livraison_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("type_remise", models.CharField(default="POURCENTAGE", max_length=20)),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=14)),
                ("actif", models.BooleanField(default=True)),
                ("date_expiration", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Magasin",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=120)),
                ("adresse", models.CharField(blank=True, max_length=255)),
                ("telephone", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="points_fidelite",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="monnaie_rendue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="sale",
            name="monnaie_rendue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="sale",
            name="montant_recu",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="sale",
            name="proforma_commercial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proformas",
                to="pos.user",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="statut",
            field=models.CharField(default="VALIDEE", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="COMMERCIAL", max_length=20),
        ),
        migrations.CreateModel(
            name="CaisseSession",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("date_ouverture", models.DateTimeField(auto_now_add=True)),
                ("date_fermeture", models.DateTimeField(blank=True, null=True)),
                (
                    "fond_de_caisse_initial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "montant_final_especes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "ecart",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("statut", models.CharField(default="OUVERTE", max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "caissier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pos.user"
                    ),
                ),
                (
                    "magasin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pos.magasin",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="caisse_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pos.caissesession",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pos.coupon",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="magasin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pos.magasin",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="magasin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pos.magasin",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="magasin_dest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements_in",
                to="pos.magasin",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="magasin_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements_out",
                to="pos.magasin",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="magasin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pos.magasin",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="magasin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pos.magasin",
            ),
        ),
        migrations.CreateModel(
            name="ServiceContract",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("reference", models.CharField(max_length=32, unique=True)),
                ("titre", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "type_service",
                    models.CharField(default="DEPLOIEMENT", max_length=80),
                ),
                (
                    "montant",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("statut", models.CharField(default="EN_COURS", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pos.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("reference", models.CharField(max_length=40, unique=True)),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=14)),
                ("statut", models.CharField(default="EFFECTUE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "demandeur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pos.user",
                    ),
                ),
                (
                    "magasin_dest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="pos.magasin",
                    ),
                ),
                (
                    "magasin_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="pos.magasin",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pos.product"
                    ),
                ),
            ],
        ),
    ]
